name: "PR (un)labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        configuration-path: .github/labeler.yaml

  # TODO:
  remove_merge_label:
    if: github.event.label.name == 'merge'
    runs-on: ubuntu-latest
