# TODO:
# store step output
# https://stackoverflow.com/a/57989070
# create issue/pr comment: https://octokit.github.io/rest.js/v18#issues-create-comment
# update review comment: https://octokit.github.io/rest.js/v18#pulls-update-review-comment
name: "Verify PR Branch Name"
on:
  pull_request_target:
    branches:
      - master
      - develop
jobs:
  verify_develop_head_name:
    runs-on: ubuntu-latest
    steps:
      - name: Verify develop head branch name
        if: github.base_ref == 'develop'
        run: |
          if [[ $GITHUB_HEAD_REF == feature/* ]] \
          || [[ $GITHUB_HEAD_REF == bugfix/* ]] \
          || [[ $GITHUB_HEAD_REF == backmerge/* ]] \
          || [[ $GITHUB_HEAD_REF == master ]]
          then
            echo "# :white_check_mark: Success" >> $GITHUB_STEP_SUMMARY
            echo "\`$GITHUB_HEAD_REF\` is a valid branch to merge in to \`$GITHUB_BASE_REF\`." \
              >> $GITHUB_STEP_SUMMARY
          else
            echo "# :x: Failure" >> $GITHUB_STEP_SUMMARY
            echo "\`$GITHUB_HEAD_REF\` is **not** a valid branch to merge in to \`$GITHUB_BASE_REF\`." \
              >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## Valid branch patterns" >> $GITHUB_STEP_SUMMARY
            echo '- `feature/*`' >> $GITHUB_STEP_SUMMARY
            echo '- `bugfix/*`' >> $GITHUB_STEP_SUMMARY
            echo '- `backmerge/*`' >> $GITHUB_STEP_SUMMARY
            echo '- `master`' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Verify master head branch name
        if: github.base_ref == 'master'
        run: |
          if [[ $GITHUB_HEAD_REF == release/* ]] \
          || [[ $GITHUB_HEAD_REF == hotfix/* ]]
          then
            echo "# :white_check_mark: Success" >> $GITHUB_STEP_SUMMARY
            echo "\`$GITHUB_HEAD_REF\` is a valid branch to merge in to \`$GITHUB_BASE_REF\`." \
              >> $GITHUB_STEP_SUMMARY
          else
            echo "# :x: Failure" >> $GITHUB_STEP_SUMMARY
            echo "\`$GITHUB_HEAD_REF\` is **not** a valid branch to merge in to \`$GITHUB_BASE_REF\`." \
              >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "## Valid branch patterns" >> $GITHUB_STEP_SUMMARY
            echo '- `release/*`' >> $GITHUB_STEP_SUMMARY
            echo '- `hotfix/*`' >> $GITHUB_STEP_SUMMARY

            exit 1
          fi

      - name: Create workflow status PR comment
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            console.log('whats context?', context);
            const { owner, repo, number } = context;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: 'Testign creating a comment!',
            })

            const pull = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            console.log('pull?', JSON.stringify(pull, null, 2));

